language: c++
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
fuzz_targets:
  - frame_fuzzer
  - batch_fuzzer
  - index_fuzzer
  - query_fuzzer
  - schema_fuzzer
  - writer_fuzzer
  - repair_fuzzer
